#author shenjinqi
# https://github.com/maxyermayank/docker-compose-elasticsearch-kibana/blob/master/docker-compose.yml#L12
version: "3" #版本号
services:
  elasticsearch:
    image: elasticsearch:7.2.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/home/shenjinqi/data/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  es02:
    image: elasticsearch:7.2.0
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/home/shenjinqi/data/elasticsearch/data
    networks:
      - esnet

 
  kibana: #服务名称（不是容器名）
    image: kibana:7.2.0  #使用的镜像
    ports:
      - "5601:5601"  #暴露的端口信息和docker run -d -p 80:80 一样
    restart: "always" #重启策略，能够使服务保持始终运行，生产环境推荐使用
    container_name: kibana #容器名称
    #挂载文件
    volumes:  
      - /home/shenjinqi/work/ELK/kibana.yml:/etc/kibana/kibana.yml
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://es01:9200/
    networks:
      - esnet
  logstash: #服务名称（不是容器名）
    image: logstash:7.2.0  #使用的镜像
    #image: logstash_sjq:1.0
    restart: "always" #重启策略，能够使服务保持始终运行，生产环境推荐使用
    container_name: logstash #容器名称
    ports:
      - "5000:5000"
    #挂载文件1.自定义配置文件 2.logstash启动配置文件 3.文件读取的挂载路径
    volumes:  
      #- /home/shenjinqi/work/ELK/logstash.conf:/etc/logstash/conf.d/logstash.conf    
      #- /home/shenjinqi/work/ELK/logstash.yml:/etc/logstash/logstash.yml   
      #- /home/shenjinqi/work/ELK/1.txt:/etc/logstash/1.txt 
      - ./config/:/usr/share/logstash/pipeline/
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      #- ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
     
    networks:
      - esnet

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  esnet:

