#author shenjinqi
# https://www.elastic.co/guide/en/elasticsearch/reference/7.2/docker.html
version: "3" #版本号
services: 
  elasticsearch: #服务名称（不是容器名）
    image: elasticsearch:7.2.0  #使用的镜像
    ports:
      - "9200:9200"  #暴露的端口信息和docker run -d -p 80:80 一样
#    restart: "always" #重启策略，能够使服务保持始终运行，生产环境推荐使用
    container_name: es_single #容器名称
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /home/shenjinqi/data/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - elknet
  kibana: #服务名称（不是容器名）
    image: kibana:7.2.0  #使用的镜像
    ports:
      - "5601:5601"  #暴露的端口信息和docker run -d -p 80:80 一样
    restart: "always" #重启策略，能够使服务保持始终运行，生产环境推荐使用
    container_name: kibana #容器名称
    #挂载文件
    volumes:  
      - /home/shenjinqi/work/ELK/kibana.yml:/etc/kibana/kibana.yml
    links:
      - elasticsearch  #容器关联es01是别名
    depends_on:
      - elasticsearch
    networks:
      - elknet
  logstash: #服务名称（不是容器名）
    image: logstash:7.2.0  #使用的镜像
    restart: "always" #重启策略，能够使服务保持始终运行，生产环境推荐使用
    container_name: logstash #容器名称
    #挂载文件1.自定义配置文件 2.logstash启动配置文件 3.文件读取的挂载路径
    volumes:  
      - /home/shenjinqi/work/ELK/logstash.conf:/etc/logstash/conf.d/logstash.conf    
      - /home/shenjinqi/work/ELK/logstash.yml:/etc/logstash/logstash.yml   
      - /home/shenjinqi/work/ELK/1.txt:/etc/logstash/1.txt 
    links:
      - elasticsearch #容器关联es01是别名
    depends_on:
      - elasticsearch
    networks:
      - elknet

networks:
    elknet:
